# Generated by Django 4.2.9 on 2024-02-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_remove_coupon_applicable_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='user_count',
            field=models.IntegerField(default=0),
        ),
    ]
