# Generated by Django 4.2.9 on 2024-01-28 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('br_name', models.CharField(max_length=200)),
                ('br_logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('br_dsc', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cat_dsc', models.TextField(blank=True, max_length=200)),
                ('published', models.BooleanField(default=True)),
                ('cat_img', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('sale_price', models.FloatField()),
                ('prodvar_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='category.brand')),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodcat', to='category.category')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=100)),
                ('sub_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcat', to='category.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVarient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Color', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=5)),
                ('stock', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('prodvar_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_varient', to='category.products')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='subcat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prosubcat', to='category.subcategory'),
        ),
    ]
