# Generated by Django 4.2.9 on 2024-01-31 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='prodvar_img',
            new_name='prod1_img',
        ),
        migrations.AddField(
            model_name='products',
            name='prod2_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='products',
            name='prod3_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_img',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='sub_img',
            field=models.ImageField(blank=True, null=True, upload_to='subcat_images/'),
        ),
    ]
