# Generated by Django 4.2.9 on 2024-02-01 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_rename_prodvar_img_products_prod1_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_image/')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_color', to='category.color')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='brand',
            name='br_dsc',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='br_logo',
        ),
        migrations.RemoveField(
            model_name='products',
            name='price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='prod1_img',
        ),
        migrations.RemoveField(
            model_name='products',
            name='prod2_img',
        ),
        migrations.RemoveField(
            model_name='products',
            name='prod3_img',
        ),
        migrations.RemoveField(
            model_name='products',
            name='sale_price',
        ),
        migrations.AlterField(
            model_name='products',
            name='brand_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand', to='category.brand'),
        ),
        migrations.DeleteModel(
            name='ProductVarient',
        ),
        migrations.AddField(
            model_name='productvar',
            name='prod_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_varient', to='category.products'),
        ),
        migrations.AddField(
            model_name='productvar',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_size', to='category.size'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='img_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='category.products'),
        ),
    ]
