# Generated by Django 4.2.9 on 2024-02-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_products_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvar',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
