# Generated by Django 4.2.9 on 2024-02-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_productvar_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvar',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
