# Generated by Django 4.2.9 on 2024-02-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_mamngmnt', '0004_alter_order_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='grand_total',
            field=models.FloatField(null=True),
        ),
    ]
