# Generated by Django 4.2.9 on 2024-02-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_mamngmnt', '0005_order_grand_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
