# Generated by Django 4.2.9 on 2024-02-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_mamngmnt', '0006_orderproduct_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tax',
            field=models.FloatField(max_length=6, null=True),
        ),
    ]
