# Generated by Django 4.2.9 on 2024-03-05 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_mamngmnt', '0014_order_delivery_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_date',
            new_name='delivery_date_s',
        ),
    ]
