# Generated by Django 4.2.9 on 2024-03-06 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_mamngmnt', '0015_rename_delivery_date_order_delivery_date_s'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_date_s',
        ),
    ]
