# Generated by Django 4.2.9 on 2024-01-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x7fcc2dab2a60>', max_length=200),
        ),
    ]
