# Generated by Django 4.2.9 on 2024-01-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_profiles_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x7fe0848faa60>', max_length=200),
        ),
    ]
