# Generated by Django 4.2.9 on 2024-02-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_cart_total_price_cart_total_qnty'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='item_total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
