# Generated by Django 4.2.9 on 2024-02-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_useraddress_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='house_name',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
