# Generated by Django 4.2.9 on 2024-02-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_useraddress_house_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='country',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
