# Generated by Django 4.2.9 on 2024-02-14 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_useraddress_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='city',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='country',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='district',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='house_name',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='landmark',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='state',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='street',
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_name', models.CharField(default='none', max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('landmark', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(default='none', max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
