# Generated by Django 4.2.9 on 2024-02-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_cart_tax_cartitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupon_count',
            field=models.IntegerField(default=0),
        ),
    ]
