# Generated by Django 4.2.9 on 2024-02-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_cart_coupon_cart_total_cart_coupon_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupon_applied',
            field=models.BooleanField(default=False),
        ),
    ]
