# Generated by Django 4.2.9 on 2024-02-25 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0006_alter_coupon_purchase_count'),
        ('home', '0019_cart_coupon_applied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='coupon_applied',
        ),
        migrations.AddField(
            model_name='cart',
            name='applied_coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applied_coupon', to='coupons.coupon'),
        ),
    ]
