# Generated by Django 4.2.9 on 2024-02-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_remove_cart_coupon_applied_cart_applied_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, null=True),
        ),
    ]
